### ISSUE TITLE
create generic testing module for jest

### ISSUE THREAD

**Issue by brendan1538** [brendan1538/cicd-pipeline#1]
possible yaml config example:

```
test:
  use:
    - jest-test
  jest-test:
    env: prod
    project: my_project
    report_emails:
      - test@jesttest.com
      - test2@jesttest.com
```
