### ISSUE TITLE
create tree-install module

### ISSUE THREAD

**Issue by brendan1538** [brendan1538/cicd-pipeline#2]
module to npm install in multiple nested directories (useful for git submodules and other forms of nested projects)

```
use: tree-install
tree-install:
  use: npm
  env: production
  dirs:
    - /sumdir
    - /sumdir/subdir
```
